/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to the appropriate I/O comport (0-3). */
/* #undef CONFIG_COMPORT */

/* Baud rate for comport (typically 115200, 57600, or 38400). */
/* #undef CONFIG_COMSPEED */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME "Pistachio"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Pistachio 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "pistachio"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"
